/*
 * This file was automatically generated by EvoSuite
 * Thu Mar 27 20:10:14 GMT 2025
 */

package org.joda.time.convert;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.time.chrono.ChronoLocalDate;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.joda.time.DateTimeZone;
import org.joda.time.LocalDate;
import org.joda.time.convert.CalendarConverter;
import org.joda.time.convert.Converter;
import org.joda.time.convert.ConverterSet;
import org.joda.time.convert.DateConverter;
import org.joda.time.convert.LongConverter;
import org.joda.time.convert.NullConverter;
import org.joda.time.convert.ReadableDurationConverter;
import org.joda.time.convert.ReadableIntervalConverter;
import org.joda.time.convert.ReadablePeriodConverter;
import org.joda.time.convert.StringConverter;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ConverterSet_ESTest extends ConverterSet_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Class<ConverterSet.Entry> class0 = Class.class;
      CalendarConverter calendarConverter0 = CalendarConverter.INSTANCE;
      ConverterSet.Entry converterSet_Entry0 = new ConverterSet.Entry(class0, calendarConverter0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Converter[] converterArray0 = new Converter[0];
      ConverterSet converterSet0 = new ConverterSet(converterArray0);
      int int0 = converterSet0.size();
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Converter[] converterArray0 = new Converter[1];
      ConverterSet converterSet0 = new ConverterSet(converterArray0);
      ConverterSet converterSet1 = converterSet0.remove(0, converterArray0);
      assertNotSame(converterSet0, converterSet1);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      ConverterSet converterSet0 = new ConverterSet((Converter[]) null);
      // Undeclared exception!
      try { 
        converterSet0.size();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.joda.time.convert.ConverterSet", e);
      }
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Converter[] converterArray0 = new Converter[1];
      ConverterSet converterSet0 = new ConverterSet(converterArray0);
      // Undeclared exception!
      try { 
        converterSet0.remove((Converter) null, (Converter[]) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.joda.time.convert.ConverterSet", e);
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Converter[] converterArray0 = new Converter[0];
      ConverterSet converterSet0 = new ConverterSet(converterArray0);
      ReadableIntervalConverter readableIntervalConverter0 = ReadableIntervalConverter.INSTANCE;
      // Undeclared exception!
      try { 
        converterSet0.remove(readableIntervalConverter0, converterArray0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 0
         //
         verifyException("org.joda.time.convert.ConverterSet", e);
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      ConverterSet converterSet0 = new ConverterSet((Converter[]) null);
      Converter[] converterArray0 = new Converter[2];
      // Undeclared exception!
      try { 
        converterSet0.remove(3142, converterArray0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.joda.time.convert.ConverterSet", e);
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Converter[] converterArray0 = new Converter[1];
      CalendarConverter calendarConverter0 = new CalendarConverter();
      converterArray0[0] = (Converter) calendarConverter0;
      ConverterSet converterSet0 = new ConverterSet(converterArray0);
      ConverterSet converterSet1 = converterSet0.remove(converterArray0[0], converterArray0);
      // Undeclared exception!
      try { 
        converterSet1.remove((-13), (Converter[]) null);
        fail("Expecting exception: NegativeArraySizeException");
      
      } catch(NegativeArraySizeException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.joda.time.convert.ConverterSet", e);
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Converter[] converterArray0 = new Converter[0];
      ConverterSet converterSet0 = new ConverterSet(converterArray0);
      // Undeclared exception!
      try { 
        converterSet0.remove((-2659), converterArray0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // -2659
         //
         verifyException("org.joda.time.convert.ConverterSet", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      ConverterSet converterSet0 = new ConverterSet((Converter[]) null);
      // Undeclared exception!
      try { 
        converterSet0.copyInto((Converter[]) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.joda.time.convert.ConverterSet", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Converter[] converterArray0 = new Converter[4];
      ConverterSet converterSet0 = new ConverterSet(converterArray0);
      Converter[] converterArray1 = new Converter[2];
      // Undeclared exception!
      try { 
        converterSet0.copyInto(converterArray1);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      ConverterSet converterSet0 = new ConverterSet((Converter[]) null);
      LongConverter longConverter0 = LongConverter.INSTANCE;
      // Undeclared exception!
      try { 
        converterSet0.add(longConverter0, (Converter[]) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.joda.time.convert.ConverterSet", e);
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Converter[] converterArray0 = new Converter[0];
      ConverterSet converterSet0 = new ConverterSet(converterArray0);
      DateConverter dateConverter0 = new DateConverter();
      // Undeclared exception!
      try { 
        converterSet0.add(dateConverter0, converterArray0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 0
         //
         verifyException("org.joda.time.convert.ConverterSet", e);
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Converter[] converterArray0 = new Converter[2];
      StringConverter stringConverter0 = StringConverter.INSTANCE;
      converterArray0[1] = (Converter) stringConverter0;
      ConverterSet converterSet0 = new ConverterSet(converterArray0);
      Class<String> class0 = String.class;
      Converter converter0 = converterSet0.select(class0);
      assertSame(converter0, stringConverter0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Converter[] converterArray0 = new Converter[1];
      ConverterSet converterSet0 = new ConverterSet(converterArray0);
      // Undeclared exception!
      try { 
        converterSet0.remove(1321, converterArray0);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.joda.time.convert.ConverterSet", e);
      }
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Converter[] converterArray0 = new Converter[4];
      ReadableDurationConverter readableDurationConverter0 = ReadableDurationConverter.INSTANCE;
      converterArray0[3] = (Converter) readableDurationConverter0;
      ConverterSet converterSet0 = new ConverterSet(converterArray0);
      Class<ChronoLocalDate> class0 = ChronoLocalDate.class;
      // Undeclared exception!
      try { 
        converterSet0.select(class0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.joda.time.convert.ConverterSet", e);
      }
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      Converter[] converterArray0 = new Converter[1];
      CalendarConverter calendarConverter0 = new CalendarConverter();
      converterArray0[0] = (Converter) calendarConverter0;
      ConverterSet converterSet0 = new ConverterSet(converterArray0);
      ConverterSet converterSet1 = converterSet0.remove(converterArray0[0], converterArray0);
      // Undeclared exception!
      try { 
        converterSet1.remove(0, converterArray0);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.joda.time.convert.ConverterSet", e);
      }
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      Converter[] converterArray0 = new Converter[1];
      CalendarConverter calendarConverter0 = new CalendarConverter();
      converterArray0[0] = (Converter) calendarConverter0;
      ConverterSet converterSet0 = new ConverterSet(converterArray0);
      ConverterSet converterSet1 = converterSet0.remove(converterArray0[0], converterArray0);
      ConverterSet converterSet2 = converterSet1.remove((Converter) null, converterArray0);
      assertNotSame(converterSet2, converterSet0);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      Converter[] converterArray0 = new Converter[4];
      NullConverter nullConverter0 = new NullConverter();
      converterArray0[3] = (Converter) nullConverter0;
      ConverterSet converterSet0 = new ConverterSet(converterArray0);
      ConverterSet converterSet1 = converterSet0.remove(converterArray0[3], converterArray0);
      assertNotSame(converterSet0, converterSet1);
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      Converter[] converterArray0 = new Converter[1];
      CalendarConverter calendarConverter0 = new CalendarConverter();
      converterArray0[0] = (Converter) calendarConverter0;
      ConverterSet converterSet0 = new ConverterSet(converterArray0);
      ConverterSet converterSet1 = converterSet0.remove(converterArray0[0], converterArray0);
      ConverterSet converterSet2 = converterSet1.remove((Converter) null, (Converter[]) null);
      assertSame(converterSet2, converterSet1);
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      Converter[] converterArray0 = new Converter[1];
      CalendarConverter calendarConverter0 = new CalendarConverter();
      converterArray0[0] = (Converter) calendarConverter0;
      ConverterSet converterSet0 = new ConverterSet(converterArray0);
      ConverterSet converterSet1 = converterSet0.remove(converterArray0[0], converterArray0);
      ConverterSet converterSet2 = converterSet1.add((Converter) null, (Converter[]) null);
      assertNotSame(converterSet1, converterSet2);
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      Converter[] converterArray0 = new Converter[7];
      ReadableIntervalConverter readableIntervalConverter0 = new ReadableIntervalConverter();
      ReadableIntervalConverter readableIntervalConverter1 = ReadableIntervalConverter.INSTANCE;
      converterArray0[1] = (Converter) readableIntervalConverter1;
      LongConverter longConverter0 = new LongConverter();
      converterArray0[0] = (Converter) longConverter0;
      ConverterSet converterSet0 = new ConverterSet(converterArray0);
      ConverterSet converterSet1 = converterSet0.add(readableIntervalConverter0, (Converter[]) null);
      assertNotSame(converterSet1, converterSet0);
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      Converter[] converterArray0 = new Converter[4];
      ReadableIntervalConverter readableIntervalConverter0 = ReadableIntervalConverter.INSTANCE;
      converterArray0[0] = (Converter) readableIntervalConverter0;
      NullConverter nullConverter0 = NullConverter.INSTANCE;
      converterArray0[1] = (Converter) nullConverter0;
      ReadableDurationConverter readableDurationConverter0 = ReadableDurationConverter.INSTANCE;
      converterArray0[2] = (Converter) readableDurationConverter0;
      ReadableDurationConverter readableDurationConverter1 = new ReadableDurationConverter();
      converterArray0[3] = (Converter) readableDurationConverter1;
      ConverterSet converterSet0 = new ConverterSet(converterArray0);
      ConverterSet converterSet1 = converterSet0.add(converterArray0[3], converterArray0);
      assertNotSame(converterSet1, converterSet0);
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      Converter[] converterArray0 = new Converter[1];
      CalendarConverter calendarConverter0 = new CalendarConverter();
      converterArray0[0] = (Converter) calendarConverter0;
      ConverterSet converterSet0 = new ConverterSet(converterArray0);
      ConverterSet converterSet1 = converterSet0.add(calendarConverter0, (Converter[]) null);
      assertSame(converterSet1, converterSet0);
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      Converter[] converterArray0 = new Converter[4];
      ReadablePeriodConverter readablePeriodConverter0 = ReadablePeriodConverter.INSTANCE;
      converterArray0[0] = (Converter) readablePeriodConverter0;
      DateConverter dateConverter0 = DateConverter.INSTANCE;
      converterArray0[1] = (Converter) dateConverter0;
      LongConverter longConverter0 = LongConverter.INSTANCE;
      converterArray0[2] = (Converter) longConverter0;
      ConverterSet converterSet0 = new ConverterSet(converterArray0);
      ConverterSet converterSet1 = converterSet0.add(converterArray0[2], converterArray0);
      assertSame(converterSet1, converterSet0);
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      Converter[] converterArray0 = new Converter[1];
      CalendarConverter calendarConverter0 = new CalendarConverter();
      converterArray0[0] = (Converter) calendarConverter0;
      ConverterSet converterSet0 = new ConverterSet(converterArray0);
      NullConverter nullConverter0 = new NullConverter();
      ConverterSet converterSet1 = converterSet0.add(nullConverter0, converterArray0);
      ConverterSet converterSet2 = converterSet1.remove(calendarConverter0, converterArray0);
      assertNotSame(converterSet2, converterSet1);
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      Converter[] converterArray0 = new Converter[4];
      DateTimeZone dateTimeZone0 = DateTimeZone.UTC;
      LocalDate localDate0 = new LocalDate(converterArray0[1], dateTimeZone0);
      assertEquals(3, localDate0.size());
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      Converter[] converterArray0 = new Converter[4];
      ReadableDurationConverter readableDurationConverter0 = new ReadableDurationConverter();
      converterArray0[1] = (Converter) readableDurationConverter0;
      DateTimeZone dateTimeZone0 = DateTimeZone.UTC;
      LocalDate localDate0 = null;
      try {
        localDate0 = new LocalDate(converterArray0[1], dateTimeZone0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // No partial converter found for type: org.joda.time.convert.ReadableDurationConverter
         //
         verifyException("org.joda.time.convert.ConverterManager", e);
      }
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      Converter[] converterArray0 = new Converter[1];
      CalendarConverter calendarConverter0 = new CalendarConverter();
      converterArray0[0] = (Converter) calendarConverter0;
      ConverterSet converterSet0 = new ConverterSet(converterArray0);
      Converter converter0 = converterSet0.select((Class<?>) null);
      assertNull(converter0);
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      Converter[] converterArray0 = new Converter[7];
      ConverterSet converterSet0 = new ConverterSet(converterArray0);
      int int0 = converterSet0.size();
      assertEquals(7, int0);
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      Converter[] converterArray0 = new Converter[1];
      ConverterSet converterSet0 = new ConverterSet(converterArray0);
      converterSet0.copyInto(converterArray0);
      assertEquals(1, converterArray0.length);
  }
}
